### ISSUE TITLE
out of memory error on some figures

### ISSUE THREAD

**Issue by nathandunn** [INCATools/figtools#3]
This is running with 2 Gb of memory.   Wondering if its holding all of the images in memory instead of streaming?

```
Downloading article 4096890 to folder /Users/nathandunn/repositories/figtools/bin/figures/4096890

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
```

**Comment by nathandunn** [comment]
This is not high priority (just an optimization).   Upping the memory to 4 Gbs enabled the download of the remainder of the figures.

**Comment by benwbooth** [comment]
Thanks @nathandunn. We may want to switch to another HTTP request library. Right now I'm using STTP. It looks like switching to another STTP backend may help with the out of memory issues:

https://sttp.readthedocs.io/en/latest/requests/streaming.html

**Comment by benwbooth** [comment]
I switched to using the [requests](https://github.com/lihaoyi/requests-scala) library. This one seems simpler to use and has streaming capabilities. So this should fix the out of memory issue.
