### ISSUE TITLE
upgrade to use imagej2 and use headless mode

### ISSUE THREAD

**Issue by nathandunn** [INCATools/figtools#4]
Would be good to do this in headless mode and not use xvfb:

https://forum.image.sc/t/a-problem-running-imagej-in-headless-mode/3909/18

https://imagej.net/ImageJ2

https://mvnrepository.com/artifact/net.imagej/imagej/2.0.0-rc-68

**Comment by nathandunn** [comment]
https://mvnrepository.com/artifact/net.imagej/imagej/2.0.0-rc-68

**Comment by nathandunn** [comment]
Can probably use https://imagej.net/ImgLib2 directly.  

Looks like we use a lot of swing in there at the moment.

**Comment by benwbooth** [comment]
The swing is mainly for visually debugging the analyze command. I'm working on converting figtools to ImageJ2. It's almost working, just a few things to fix, then I'll test if headless mode works.

**Comment by benwbooth** [comment]
OK I got this working. Now I just need to write some tests.
